export const cities = [
  { value: "amsterdam", label: "Amsterdam" },
  { value: "bangkok", label: "Bangkok" },
  { value: "barcelona", label: "Barcelona" },
  { value: "barisal", label: "Barisal" },
  { value: "beijing", label: "Beijing" },
  { value: "berlin", label: "Berlin" },
  { value: "buenos-aires", label: "Buenos Aires" },
  { value: "cairo", label: "Cairo" },
  { value: "comilla", label: "Comilla" },
  { value: "cox's-bazar", label: "Cox's Bazar" },
  { value: "delhi", label: "Delhi" },
  { value: "dhaka", label: "Dhaka" },
  { value: "dubai", label: "Dubai" },
  { value: "gazipur", label: "Gazipur" },
  { value: "hong-kong", label: "Hong Kong" },
  { value: "istanbul", label: "Istanbul" },
  { value: "jakarta", label: "Jakarta" },
  { value: "kuala-lumpur", label: "Kuala Lumpur" },
  { value: "khulna", label: "Khulna" },
  { value: "london", label: "London" },
  { value: "los-angeles", label: "Los Angeles" },
  { value: "manila", label: "Manila" },
  { value: "mexico-city", label: "Mexico City" },
  { value: "moscow", label: "Moscow" },
  { value: "mumbai", label: "Mumbai" },
  { value: "mymensingh", label: "Mymensingh" },
  { value: "narayanganj", label: "Narayanganj" },
  { value: "new-york", label: "New York" },
  { value: "paris", label: "Paris" },
  { value: "rajshahi", label: "Rajshahi" },
  { value: "rangpur", label: "Rangpur" },
  { value: "rio-de-janeiro", label: "Rio de Janeiro" },
  { value: "rome", label: "Rome" },
  { value: "são-paulo", label: "São Paulo" },
  { value: "seoul", label: "Seoul" },
  { value: "shanghai", label: "Shanghai" },
  { value: "singapore", label: "Singapore" },
  { value: "sydney", label: "Sydney" },
  { value: "sylhet", label: "Sylhet" },
  { value: "tokyo", label: "Tokyo" },
  { value: "toronto", label: "Toronto" },
];